apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: production-api-asg
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: production-api
        node: asg
    spec: 
      containers: 
        - name: production-nginx
          image: ttndfame/nginx:latest
          ports: 
          - containerPort: 80
          env:
          - name: ENV_NAME
            value:  production
          - name: MODULE
            value:  api
        - name: production-api
          image: ttndfame/production_api:v5.22.13
          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 200
            timeoutSeconds: 1
          ports:
          - containerPort: 8080
          env:
          - name: ENV_NAME
            value:  production
          - name: MODULE
            value:  api
          volumeMounts:
          - mountPath: /opt/jetty/logs
            name: production-api-volume
      volumes:
      - name: production-api-volume
        hostPath:
          path: /var/log/app/api_logs
      nodeSelector:
        node: asg
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: production-api-spot
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: production-api
        node: spot
    spec: 
      containers: 
        - name: production-nginx
          image: ttndfame/nginx:latest
          ports: 
          - containerPort: 80
          env:
          - name: ENV_NAME
            value:  production
          - name: MODULE
            value:  api
        - name: production-api
          image: ttndfame/production_api:v5.22.13
          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 200
            timeoutSeconds: 1
          ports:
          - containerPort: 8080
          env:
          - name: ENV_NAME
            value:  production
          - name: MODULE
            value:  api
          volumeMounts:
          - mountPath: /opt/jetty/logs
            name: production-api-volume
      volumes:
      - name: production-api-volume
        hostPath:
          path: /var/log/app/api_logs
      nodeSelector:
        node: spot
---
apiVersion: v1
kind: Service
metadata:
  name: production-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:iam::442793157362:server-certificate/livfame_2016
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 8080
    - name: "https"
      port: 443
      targetPort: 8080
  type: LoadBalancer
  selector:
    run: production-api
