apiVersion: v1
kind: Service
metadata:
  name: qa-beamdetail
spec:
  ports:
    - name: "www"
      port: 80
      targetPort: 80
  selector:
    run: qa-beamdetail
  type: externalIPs 
  #externalIPs: 
  # - 80.11.12.10
