apiVersion: v1
kind: Service
metadata:
  name: qa-monetizationadmin
spec:
  ports:
    - name: "www"
      port: 80
      targetPort: 8080
  selector:
    run: qa-monetizationadmin
  type: LoadBalancer
