Version: extensions/v1beta1
kind: Ingress
metadata:
  name: infraingress
spec:
  rules:
  - host: redacted.test.com
    http:
      paths:
      - path: /
        backend:
          serviceName: service1
          servicePort: 80
      - path: /notebooks
        backend:
          serviceName: service2
          servicePort: 8888
  - host: redacted2.test.com
    http:
      paths:
      - path: /
        backend:
          serviceName: service3
          servicePort: 80
      - path: /help
        backend:
          serviceName: service4
          servicePort: 8888
          servicePort: 80
