apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qa-beamarchive
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: qa-beamarchive
    spec:
      containers:
      - name: qa-beamarchive
        image: ttndfame/qa_beamarchive:qa-12.17.98
        ports:
        - containerPort:  8080
        env:
        - name: ENV_NAME
          value:  qa
        - name: MODULE
          value:  beamarchive
