apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qa-beamdetail
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: qa-beamdetail
    spec: 
      containers: 
        - name: qa-nginx
          image: ttndfame/nginx:latest
          ports: 
          - containerPort: 80
          env:
          - name: ENV_NAME
            value:  qa
          - name: MODULE
            value:  beamdetail
        - name: qa-beamdetail
          image: ttndfame/qa_beamdetail:qa-12.17.46
          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 200
            timeoutSeconds: 1
          ports:
          - containerPort: 8080
          env:
          - name: ENV_NAME
            value:  qa
          - name: MODULE
            value:  beamdetail
