apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qa-moderator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: qa-moderator
    spec:
      containers:
      - name: qa-moderator
        image: ttndfame/qa_moderator:qa-12.17.6
        ports:
        - containerPort:  8080
        env:
        - name: ENV_NAME
          value:  qa
        - name: MODULE
          value:  moderator
