apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qa-moderator
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: qa-moderator
    spec:
      containers:
      - name: qa-moderator
        image: ttndfame/qa_moderator:qa-12.17.6
        ports:
        - containerPort:  8080
        readinessProbe:
          httpGet:
            path: /heartbeat
            port: 8080
          initialDelaySeconds: 200
          timeoutSeconds: 1
        env:
        - name: ENV_NAME
          value:  qa
        - name: MODULE
          value:  moderator
