apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qa-unomailer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: qa-unomailer
    spec:
      containers:
      - name: qa-unomailer
        image: ttndfame/qa_unomailer:qa-12.3.4
        ports:
        - containerPort:  8080
        env:
        - name: ENV_NAME
          value:  qa
        - name: MODULE
          value:  unomailer
