apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: mytest
spec:
  imagePullSecrets:
    - name: mysecret
  containers:
    - name: mytest1
      image: mysecret/ttndfame/qa_admin:qa-12.17.30
      ports:
        - containerPort: 80
