FROM ubuntu:14.04
MAINTAINER Rakesh Mahajan
RUN apt-get update
RUN apt-get install -y software-properties-common python-software-properties
RUN apt-add-repository ppa:bhadauria-nitin/nginx-lua
RUN apt-get update && apt-get install -y \
telnet \
vim \
nginx=1.4.6-1ubuntu3.4-luajit \
luarocks \
python-pip
RUN /usr/bin/pip install awscli
RUN luarocks install luasocket
RUN wget -O /opt/startNginx.sh https://s3.amazonaws.com/fameplus-kubernetes/nginx/startNginx.sh
RUN chmod 755 /opt/startNginx.sh
RUN rm -rf /etc/nginx/nginx.conf
RUN mkdir -p /etc/nginx/ssl
COPY nginx.conf /etc/nginx/nginx.conf 
ADD intermediate.crt /etc/nginx/ssl/intermediate.crt
ADD star_livfame_com.crt /etc/nginx/ssl/star_livfame_com.crt
ADD star_livfame_com.key /etc/nginx/ssl/star_livfame_com.key
CMD ["/opt/startNginx.sh"]
