FROM ubuntu:14.04
MAINTAINER Rakesh Mahajan
RUN apt-get update
RUN apt-get install -y software-properties-common python-software-properties
RUN apt-add-repository ppa:bhadauria-nitin/nginx-lua
RUN apt-get update && apt-get install -y \
telnet \
vim \
nginx=1.4.6-1ubuntu3.4-luajit \
luarocks \
python-pip
RUN /usr/bin/pip install awscli
RUN luarocks install luasocket
ADD startNginx.sh /opt/
RUN rm -rf /etc/nginx/nginx.conf 
COPY nginx.conf /etc/nginx/nginx.conf 
ADD intermediate.crt /etc/nginx/ssl
ADD star_livfame_com.crt /etc/nginx/ssl
ADD star_livfame_com.crt.key /etc/nginx/ssl
CMD ["/opt/startNginx.sh"]
