apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qa-jobs
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: qa-jobs
    spec:
      containers:
      - name: qa-jobs
        image: ttndfame/qa_jobs:qa-12.17.100
        ports:
        - containerPort:  8080
        readinessProbe:
          httpGet:
            path: /heartbeat
            port: 8080
          initialDelaySeconds: 200
          timeoutSeconds: 1
        env:
        - name: ENV_NAME
          value:  qa
        - name: MODULE
          value:  jobs
---
apiVersion: v1
kind: Service
metadata:
  name: qa-jobs
spec:
  ports:
    - name: "www"
      port: 80
      targetPort: 8080
  type: LoadBalancer
  selector:
    run: qa-jobs
