apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qa-profanity
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: qa-profanity
    spec:
      containers:
      - name: qa-profanity
        image: ttndfame/qa_profanity:qa-12.0.10
---
apiVersion: v1
kind: Service
metadata:
  name: qa-profanity
spec:
  ports:
    - name: "www"
      port: 80
      targetPort: 8080
  type: LoadBalancer
  selector:
    run: qa-profanity
