apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qa-worker1
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: qa-worker1
    spec:
      containers:
      - name: qa-worker
        image: ttndfame/qa_worker:qa-12.21.17
        ports:
        - containerPort:  8080
        readinessProbe:
          httpGet:
            path: /heartbeat
            port: 8080
          initialDelaySeconds: 200
          timeoutSeconds: 1
        env:
        - name: ENV_NAME
          value:  qa
      nodeSelector:
        node: test
