apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: uat-webappapi
  namespace: uat
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: uat-webappapi
    spec:
      containers:
      - name: uat-webappapi
        image: ttndfame/uat_webappapi:uat-6.12.26
        ports:
        - containerPort:  8080
        readinessProbe:
          httpGet:
            path: /heartbeat
            port: 8080
          initialDelaySeconds: 200
          timeoutSeconds: 1
        env:
        - name: ENV_NAME
          value: uat
        - name: MODULE
          value:  webappapi
        volumeMounts:
        - mountPath: /opt/jetty/logs
          name: uat-webappapi-volume
      volumes:
      - name: uat-webappapi-volume
        hostPath:
          path: /var/log/app/webappapi_logs
---
apiVersion: v1
kind: Service
metadata:
  name: uat-webappapi
  namespace: uat
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:iam::442793157362:server-certificate/livfame_2016
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 8080
    - name: "https"
      port: 443
      targetPort: 8080
  type: LoadBalancer
  selector:
    run: uat-webappapi
