apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: -
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: -
    spec:
      containers:
      - name: -
        image: ttndfame/_:
        ports:
        - containerPort:  8080
        readinessProbe:
          httpGet:
            path: /heartbeat
            port: 8080
          initialDelaySeconds: 200
          timeoutSeconds: 1
        env:
        - name: 
          value:  qa
        - name: 
          value:  jobs
---
apiVersion: v1
kind: Service
metadata:
  name: -
spec:
  ports:
    - name: "www"
      port: 80
      targetPort: 8080
  type: LoadBalancer
  selector:
    run: -
