apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qa-worker
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: qa-worker
    spec:
      containers:
      - name: qa-worker
        image: ttndfame/qa_worker:qa-12.21.38
        ports:
        - containerPort:  8080
        readinessProbe:
          httpGet:
            path: /heartbeat
            port: 8080
          initialDelaySeconds: 200
          timeoutSeconds: 1
        env:
        - name: qa
          value:  qa
        - name: worker
          value:  jobs
---
apiVersion: v1
kind: Service
metadata:
  name: qa-worker
spec:
  ports:
    - name: "www"
      port: 80
      targetPort: 8080
  type: LoadBalancer
  selector:
    run: qa-worker
