apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: SERVER-APP
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: SERVER-APP
    spec: 
      containers: 
        - name: SERVER-nginx
          image: ttndfame/nginx:latest
          ports: 
          - containerPort: 80
          env:
          - name: ENV_NAME
            value:  SERVER
          - name: MODULE
            value:  APP
        - name: SERVER-APP
          image: ttndfame/SERVER_APP:IMAGE
          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 200
            timeoutSeconds: 1
          ports:
          - containerPort: 8080
          env:
          - name: ENV_NAME
            value:  SERVER
          - name: MODULE
            value:  APP
---
apiVersion: v1
kind: Service
metadata:
  name: SERVER-APP
spec:
  ports:
    - name: "www"
      port: 80
      targetPort: 80
  selector:
    run: SERVER-APP
  type: LoadBalancer
